import type { SimpleScenePlan, VisualStepInput } from "./VisualizerCanvas";

export type VisualizerSample = {
  label: string;
  shortLabel: string;
  input: VisualStepInput;
  scene: SimpleScenePlan;
};

export const VISUALIZER_SAMPLES: Record<string, VisualizerSample> = {
  balance_scale: {
    label: "Persamaan Linear",
    shortLabel: "Persamaan",
    input: {
      topic: "persamaan_linear_satu_variabel",
      step_number: 1,
      socratic_question: "Bagian mana yang harus kita hilangkan dulu agar x lebih mudah ditemukan?",
      math_state: "2x + 3 = 11",
      target_concept: "mengisolasi variabel",
      expected_student_focus: "+3 di ruas kiri",
      visual_type_expected: "balance_scale",
      visual_goal: "Menunjukkan bahwa persamaan adalah dua sisi yang seimbang.",
    },
    scene: {
      component: "BalanceScaleVisualizer",
      scene_intent: "Menunjukkan bahwa 2x + 3 dan 11 adalah dua sisi yang seimbang.",
      highlight_focus: "+3 di ruas kiri",
      interaction_mode: "select",
      student_instruction: "Klik bagian yang perlu dihilangkan terlebih dahulu.",
      correct_target: "+3 di ruas kiri",
      hint: "Cari bagian yang menempel pada x tetapi bukan x.",
      success_feedback: "Benar, +3 adalah bagian yang perlu kita perhatikan agar x bisa dibuat sendirian.",
    },
  },
  fraction_bar: {
    label: "Pecahan",
    shortLabel: "Pecahan",
    input: {
      topic: "pecahan",
      step_number: 1,
      socratic_question: "Dari 4 bagian yang sama besar, berapa bagian yang diambil?",
      math_state: "3/4",
      target_concept: "makna pembilang dan penyebut",
      expected_student_focus: "angka 3 sebagai bagian yang diambil",
      visual_type_expected: "fraction_bar",
      visual_goal: "Menunjukkan bahwa 3/4 berarti 3 bagian dari 4 bagian sama besar.",
    },
    scene: {
      component: "FractionBarVisualizer",
      scene_intent: "Menunjukkan bahwa 3/4 berarti 3 bagian diambil dari 4 bagian yang sama besar.",
      highlight_focus: "3 bagian yang diambil",
      interaction_mode: "select",
      student_instruction: "Klik bagian-bagian yang diambil pada pecahan ini.",
      correct_target: "3 bagian yang diarsir",
      hint: "Perhatikan bagian yang warnanya berbeda dari keseluruhan batang.",
      success_feedback: "Benar! 3 bagian yang diambil menunjukkan pembilang dari pecahan 3/4.",
    },
  },
  number_line: {
    label: "Bilangan Bulat",
    shortLabel: "Garis Bilangan",
    input: {
      topic: "bilangan_bulat",
      step_number: 1,
      socratic_question: "Di mana posisi bilangan -3 pada garis bilangan?",
      math_state: "-3",
      target_concept: "posisi bilangan negatif pada garis bilangan",
      expected_student_focus: "posisi -3 di sebelah kiri nol",
      visual_type_expected: "number_line",
      visual_goal: "Menunjukkan bahwa bilangan negatif berada di sebelah kiri nol.",
    },
    scene: {
      component: "NumberLineVisualizer",
      scene_intent: "Menunjukkan posisi -3 pada garis bilangan.",
      highlight_focus: "posisi -3 di sebelah kiri nol",
      interaction_mode: "select",
      student_instruction: "Klik posisi yang tepat untuk bilangan -3.",
      correct_target: "titik -3",
      hint: "Bilangan negatif selalu di sebelah kiri nol.",
      success_feedback: "Benar! -3 ada di sebelah kiri nol pada garis bilangan.",
    },
  },
  coordinate_plane: {
    label: "Koordinat",
    shortLabel: "Koordinat",
    input: {
      topic: "koordinat_cartesius",
      step_number: 1,
      socratic_question: "Bagaimana cara menemukan titik (2,3) di bidang koordinat?",
      math_state: "titik (2,3)",
      target_concept: "membaca koordinat x dan y",
      expected_student_focus: "gerak 2 ke kanan dan 3 ke atas",
      visual_type_expected: "coordinate_plane",
      visual_goal: "Menunjukkan bahwa koordinat (2,3) berarti 2 ke kanan lalu 3 ke atas.",
    },
    scene: {
      component: "CoordinatePlaneVisualizer",
      scene_intent: "Menunjukkan posisi titik (2,3) pada bidang koordinat.",
      highlight_focus: "gerak 2 ke kanan dan 3 ke atas",
      interaction_mode: "select",
      student_instruction: "Klik posisi titik (2,3) pada bidang koordinat.",
      correct_target: "titik (2,3)",
      hint: "Mulai dari titik nol, gerak ke kanan dulu baru ke atas.",
      success_feedback: "Benar! Titik (2,3) artinya 2 ke kanan dan 3 ke atas dari titik asal.",
    },
  },
  geometry_shape: {
    label: "Bangun Datar",
    shortLabel: "Geometri",
    input: {
      topic: "bangun_datar",
      step_number: 1,
      socratic_question: "Bagian mana dari segitiga yang menjadi alas dan tingginya?",
      math_state: "segitiga dengan alas 8 cm dan tinggi 5 cm",
      target_concept: "luas segitiga",
      expected_student_focus: "alas dan tinggi segitiga",
      visual_type_expected: "geometry_shape",
      visual_goal: "Menunjukkan alas dan tinggi pada segitiga.",
    },
    scene: {
      component: "GeometryShapeVisualizer",
      scene_intent: "Menunjukkan alas dan tinggi pada segitiga.",
      highlight_focus: "alas dan tinggi segitiga",
      interaction_mode: "highlight",
      student_instruction: "Perhatikan bagian alas dan tinggi yang disorot.",
      correct_target: "alas dan tinggi segitiga",
      hint: "Alas di bawah, tinggi tegak lurus ke atas.",
      success_feedback: "Bagus! Alas dan tinggi segitiga sudah teridentifikasi.",
    },
  },
  area_model: {
    label: "Perkalian",
    shortLabel: "Area Model",
    input: {
      topic: "perkalian",
      step_number: 1,
      socratic_question: "Berapa banyak kotak kecil yang terbentuk dari 3 x 4?",
      math_state: "3 x 4",
      target_concept: "perkalian sebagai susunan kotak",
      expected_student_focus: "susunan 3 baris dan 4 kolom",
      visual_type_expected: "area_model",
      visual_goal: "Menunjukkan bahwa 3 x 4 membentuk 12 kotak.",
    },
    scene: {
      component: "AreaModelVisualizer",
      scene_intent: "Menunjukkan bahwa 3 x 4 membentuk grid 3 baris dan 4 kolom.",
      highlight_focus: "susunan 3 baris dan 4 kolom",
      interaction_mode: "highlight",
      student_instruction: "Hitung jumlah kotak yang terbentuk.",
      correct_target: "12 kotak",
      hint: "Hitung kotak per baris, lalu kalikan dengan jumlah baris.",
      success_feedback: "Benar! 3 x 4 = 12 kotak kecil.",
    },
  },
  angle_diagram: {
    label: "Sudut",
    shortLabel: "Sudut",
    input: {
      topic: "sudut",
      step_number: 1,
      socratic_question: "Berapa besar sudut yang terbentuk?",
      math_state: "sudut 60 derajat",
      target_concept: "mengukur besar sudut",
      expected_student_focus: "busur sudut 60 derajat",
      visual_type_expected: "angle_diagram",
      visual_goal: "Menunjukkan sudut 60 derajat pada diagram.",
    },
    scene: {
      component: "AngleDiagramVisualizer",
      scene_intent: "Menunjukkan sudut 60 derajat dengan jelas.",
      highlight_focus: "busur sudut 60 derajat",
      interaction_mode: "slider",
      student_instruction: "Geser slider untuk membuat sudut yang tepat.",
      correct_target: "sudut 60 derajat",
      hint: "Sudut lancip kurang dari 90 derajat.",
      success_feedback: "Benar! Sudut 60 derajat adalah sudut lancip.",
    },
  },
  bar_model: {
    label: "Perbandingan",
    shortLabel: "Rasio",
    input: {
      topic: "perbandingan",
      step_number: 1,
      socratic_question: "Jika perbandingan apel dan jeruk 2:3, mana yang lebih banyak?",
      math_state: "2:3",
      target_concept: "perbandingan dua besaran",
      expected_student_focus: "panjang batang perbandingan",
      visual_type_expected: "bar_model",
      visual_goal: "Menunjukkan perbandingan 2:3 secara visual.",
    },
    scene: {
      component: "BarModelVisualizer",
      scene_intent: "Menunjukkan perbandingan 2:3 dengan model batang.",
      highlight_focus: "panjang batang perbandingan",
      interaction_mode: "highlight",
      student_instruction: "Perhatikan batang mana yang lebih panjang.",
      correct_target: "batang jeruk (3 bagian)",
      hint: "Batang yang lebih panjang menunjukkan jumlah yang lebih banyak.",
      success_feedback: "Benar! Jeruk lebih banyak karena bagiannya 3, sedangkan apel 2.",
    },
  },
  table_pattern: {
    label: "Pola Bilangan",
    shortLabel: "Pola",
    input: {
      topic: "pola_bilangan",
      step_number: 1,
      socratic_question: "Apa pola yang kamu lihat pada barisan ini?",
      math_state: "2, 4, 6, 8, ...",
      target_concept: "pola bilangan genap",
      expected_student_focus: "selisih antar bilangan",
      visual_type_expected: "table_pattern",
      visual_goal: "Menunjukkan pola kenaikan bilangan.",
    },
    scene: {
      component: "TablePatternVisualizer",
      scene_intent: "Menunjukkan pola kenaikan +2 pada barisan bilangan.",
      highlight_focus: "selisih antar bilangan",
      interaction_mode: "highlight",
      student_instruction: "Perhatikan selisih antara setiap dua bilangan berurutan.",
      correct_target: "selisih +2",
      hint: "Kurangi bilangan setelahnya dengan bilangan sebelumnya.",
      success_feedback: "Benar! Setiap bilangan naik 2 dari bilangan sebelumnya.",
    },
  },
  simple_chart: {
    label: "Statistika",
    shortLabel: "Diagram",
    input: {
      topic: "statistika",
      step_number: 1,
      socratic_question: "Data mana yang paling banyak muncul?",
      math_state: "data: 3, 5, 5, 7, 5, 8",
      target_concept: "modus data",
      expected_student_focus: "nilai yang paling sering muncul",
      visual_type_expected: "simple_chart",
      visual_goal: "Menunjukkan frekuensi setiap data.",
    },
    scene: {
      component: "SimpleChartVisualizer",
      scene_intent: "Menunjukkan frekuensi setiap nilai data.",
      highlight_focus: "batang tertinggi",
      interaction_mode: "select",
      student_instruction: "Klik batang yang paling tinggi.",
      correct_target: "batang angka 5",
      hint: "Cari batang yang paling tinggi di diagram.",
      success_feedback: "Benar! Angka 5 muncul paling sering (3 kali), jadi itu modusnya.",
    },
  },
  solid_shape: {
    label: "Bangun Ruang",
    shortLabel: "Ruang",
    input: {
      topic: "bangun_ruang",
      step_number: 1,
      socratic_question: "Berapa banyak rusuk pada balok?",
      math_state: "balok dengan p=5, l=3, t=4",
      target_concept: "unsur-unsur balok",
      expected_student_focus: "rusuk-rusuk balok",
      visual_type_expected: "solid_shape",
      visual_goal: "Menunjukkan rusuk-rusuk pada balok.",
    },
    scene: {
      component: "SolidShapeVisualizer",
      scene_intent: "Menunjukkan balok dan rusuk-rusuknya.",
      highlight_focus: "rusuk-rusuk balok",
      interaction_mode: "highlight",
      student_instruction: "Hitung jumlah rusuk yang disorot.",
      correct_target: "12 rusuk",
      hint: "Balok memiliki rusuk di atas, bawah, dan sisi tegak.",
      success_feedback: "Benar! Balok memiliki 12 rusuk.",
    },
  },
};

export const DEFAULT_VISUALIZER_SAMPLE_KEY = "balance_scale";
